# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "SecretSpice" do

pod "AFNetworking"
pod "JSQMessagesViewController"
pod "PubNub"
pod "Mantle"
pod "libextobjc"
pod "SVProgressHUD"

end
